-- MySQL Script generated by MySQL Workbench
-- Thu Sep 10 14:23:26 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema circuleather
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `circuleather` ;

-- -----------------------------------------------------
-- Schema circuleather
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `circuleather` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `circuleather` ;

-- -----------------------------------------------------
-- Table `circuleather`.`vorrad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `circuleather`.`vorrad` ;

CREATE TABLE IF NOT EXISTS `circuleather`.`vorrad` (
  `idProduct` INT NOT NULL,
  `kleur` VARCHAR(45) NOT NULL,
  `gewicht in kg` DECIMAL(10,2) NOT NULL,
  `bruikbaar` VARCHAR(45) NOT NULL,
  `soort` VARCHAR(45) NOT NULL,
  `manier van looien` VARCHAR(45) NOT NULL,
  `maat` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idProduct`),
  UNIQUE INDEX `idProduct_UNIQUE` (`idProduct` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `circuleather`.`bestellingen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `circuleather`.`bestellingen` ;

CREATE TABLE IF NOT EXISTS `circuleather`.`bestellingen` (
  `idBestelling` INT NOT NULL,
  `vorrad_idProduct` INT NOT NULL,
  `prijs` DECIMAL(10,2) NOT NULL,
  `total prijs` DECIMAL(10,2) NOT NULL,
  `bestelling nummer` INT NOT NULL,
  `Datum` DATE NOT NULL,
  `klant naam` VARCHAR(45) NOT NULL,
  `rekening nummer` INT NOT NULL,
  `e-mail` VARCHAR(45) NOT NULL,
  `adres` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBestelling`),
  UNIQUE INDEX `idBestelling_UNIQUE` (`idBestelling` ASC) VISIBLE,
  UNIQUE INDEX `vorrad_idProduct_UNIQUE` (`vorrad_idProduct` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
